language: csharp
solution: src/TomKerkhove.Samples.KeyVault.sln
dotnet: 2.0.0
os:  
  - linux
branches:  
 only:
   - master
script:
 - dotnet --info
 - dotnet build src/TomKerkhove.Samples.KeyVault.sln --configuration release